# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
image:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input

cache:
  - C:\Users\appveyor\.node-gyp
  - '%AppData%\npm-cache'

environment:
  GITHUB_TOKEN:
    secure: zK6ifWCvpFMNxnHa0QTa552c5WP2mgc2tRc1I5d9QQU/STgXlHnwC9lUOF33445x

  matrix:
    - nodejs_version: 14
    - nodejs_version: 13
    - nodejs_version: 12
    - nodejs_version: 11
    - nodejs_version: 10
    - nodejs_version: 8
    - nodejs_version: 6
    - nodejs_version: 4

platform:
  - x86
  - x64

install:
  - pip install cpplint
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm run lint

deploy_script:
  - scripts\prebuild-publish.bat %nodejs_version%
